language: python
python:
  - 3.5
  - 3.6

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade async-generator pytest pytest-asyncio pytest-cov codecov -e .
  - pip install -e .

script:
  - pytest --cov=aiotftp --cov-report=term --cov-report=html --cov-append tests

after_success:
  - codecov
