language: python
python:
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly

cache:
  directories:
  - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install --upgrade async-generator hypothesis 'pytest<3.7.0' pytest-asyncio pytest-cov codecov -e .
  - pip install -e .

script:
  - pytest -v --cov=aiotftp --cov-report=term --cov-report=html --cov-append tests

after_success:
  - codecov
